[package]
name = "notification_sender_cli"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
candid = "0.7.6"
dotenv = "0.15.0"
env_logger = "0.9.0"
notification_sender = { path = "../core" }
tokio = { version = "1.10.0", features = ["macros", "time"] }
types = { path = "../../../libraries/types" }
