[package]
name = "notification_sender"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
candid = "0.7.6"
futures = "0.3.17"
garcon = "0.2.3"
ic-agent = "0.6.0"
ledger-canister = { git = "https://github.com/dfinity/ic", rev = "e362530172c44679313b1b7fca1e90d8967545d8" }
log = "0.4.14"
notifications_canister_api = { path = "../../../canisters/notifications/api" }
serde = "1.0.130"
tokio = "1.11.0"
types = { path = "../../../libraries/types" }
